import { NewsArticle } from '@app/shared';

export function getMockNews(): NewsArticle[] {
  const now = new Date();
  
  return [
    {
      id: 'mock-article-1',
      title: 'Breaking: Major Technology Breakthrough Announced',
      summary: 'Scientists have announced a groundbreaking discovery in quantum computing that could revolutionize the tech industry.',
      content: 'Scientists have announced a groundbreaking discovery in quantum computing that could revolutionize the tech industry. The new quantum processor can perform complex calculations at unprecedented speeds, opening up new possibilities for artificial intelligence and cryptography.',
      author: 'Jane Smith',
      publishedAt: new Date(now.getTime() - 60 * 60 * 1000).toISOString(),
      source: 'Tech News Daily',
      url: 'https://example.com/article-1',
      imageUrl: 'https://picsum.photos/800/600?random=1',
    },
    {
      id: 'mock-article-2',
      title: 'Global Climate Summit Reaches Historic Agreement',
      summary: 'World leaders have reached a landmark agreement on climate action, committing to ambitious carbon reduction targets.',
      content: 'World leaders have reached a landmark agreement on climate action, committing to ambitious carbon reduction targets. The agreement includes provisions for renewable energy investment, carbon pricing mechanisms, and support for developing nations in their transition to clean energy.',
      author: 'John Doe',
      publishedAt: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
      source: 'Global News Network',
      url: 'https://example.com/article-2',
      imageUrl: 'https://picsum.photos/800/600?random=2',
    },
    {
      id: 'mock-article-3',
      title: 'New Study Reveals Benefits of Mediterranean Diet',
      summary: 'A comprehensive study shows significant health benefits associated with the Mediterranean diet.',
      content: 'A comprehensive study shows significant health benefits associated with the Mediterranean diet. Researchers found that people following this diet had lower rates of heart disease, diabetes, and other chronic conditions. The diet emphasizes fruits, vegetables, whole grains, and healthy fats.',
      author: 'Dr. Sarah Johnson',
      publishedAt: new Date(now.getTime() - 3 * 60 * 60 * 1000).toISOString(),
      source: 'Health Today',
      url: 'https://example.com/article-3',
      imageUrl: 'https://picsum.photos/800/600?random=3',
    },
    {
      id: 'mock-article-4',
      title: 'Stock Markets Hit Record Highs Amid Economic Recovery',
      summary: 'Major stock indices reached new record highs as economic indicators point to strong recovery.',
      content: 'Major stock indices reached new record highs as economic indicators point to strong recovery. Investors are optimistic about corporate earnings and economic growth prospects. The Federal Reserve has indicated it will maintain supportive monetary policy.',
      author: 'Michael Brown',
      publishedAt: new Date(now.getTime() - 4 * 60 * 60 * 1000).toISOString(),
      source: 'Financial Times',
      url: 'https://example.com/article-4',
      imageUrl: 'https://picsum.photos/800/600?random=4',
    },
    {
      id: 'mock-article-5',
      title: 'Space Agency Announces Plans for Mars Colony',
      summary: 'Plans for establishing a permanent human settlement on Mars have been unveiled.',
      content: 'Plans for establishing a permanent human settlement on Mars have been unveiled. The ambitious project aims to send the first colonists to the Red Planet within the next decade. The mission will focus on developing sustainable life support systems and resource utilization technologies.',
      author: 'Dr. Emily Chen',
      publishedAt: new Date(now.getTime() - 5 * 60 * 60 * 1000).toISOString(),
      source: 'Space News',
      url: 'https://example.com/article-5',
      imageUrl: 'https://picsum.photos/800/600?random=5',
    },
    {
      id: 'mock-article-6',
      title: 'Electric Vehicle Sales Surge Globally',
      summary: 'Electric vehicle sales have increased by 50% year-over-year as adoption accelerates.',
      content: 'Electric vehicle sales have increased by 50% year-over-year as adoption accelerates. Major automakers are ramping up production of electric models, and governments are offering incentives to encourage the transition to clean transportation. Charging infrastructure is expanding rapidly.',
      author: 'Tom Anderson',
      publishedAt: new Date(now.getTime() - 6 * 60 * 60 * 1000).toISOString(),
      source: 'Auto World',
      url: 'https://example.com/article-6',
      imageUrl: 'https://picsum.photos/800/600?random=6',
    },
    {
      id: 'mock-article-7',
      title: 'AI Assistant Passes Turing Test in Landmark Achievement',
      summary: 'An advanced AI system has successfully passed the Turing Test, marking a significant milestone.',
      content: 'An advanced AI system has successfully passed the Turing Test, marking a significant milestone in artificial intelligence research. The AI demonstrated human-like conversational abilities and reasoning skills. Experts say this represents a major step forward in machine intelligence.',
      author: 'Dr. Alex Martinez',
      publishedAt: new Date(now.getTime() - 7 * 60 * 60 * 1000).toISOString(),
      source: 'AI Research Journal',
      url: 'https://example.com/article-7',
      imageUrl: 'https://picsum.photos/800/600?random=7',
    },
    {
      id: 'mock-article-8',
      title: 'Major Breakthrough in Cancer Treatment Research',
      summary: 'Researchers have developed a new immunotherapy approach showing promising results.',
      content: 'Researchers have developed a new immunotherapy approach showing promising results in clinical trials. The treatment harnesses the body\'s immune system to target cancer cells more effectively. Early results show significant tumor reduction with fewer side effects than traditional chemotherapy.',
      author: 'Dr. Lisa Wang',
      publishedAt: new Date(now.getTime() - 8 * 60 * 60 * 1000).toISOString(),
      source: 'Medical Journal',
      url: 'https://example.com/article-8',
      imageUrl: 'https://picsum.photos/800/600?random=8',
    },
    {
      id: 'mock-article-9',
      title: 'Revolutionary Solar Panel Technology Unveiled',
      summary: 'New solar panels achieve record-breaking efficiency of 40%, doubling previous standards.',
      content: 'New solar panels achieve record-breaking efficiency of 40%, doubling previous standards. The breakthrough uses advanced materials and innovative design to capture more sunlight. This technology could make solar energy more competitive with fossil fuels.',
      author: 'Robert Green',
      publishedAt: new Date(now.getTime() - 9 * 60 * 60 * 1000).toISOString(),
      source: 'Energy Today',
      url: 'https://example.com/article-9',
      imageUrl: 'https://picsum.photos/800/600?random=9',
    },
    {
      id: 'mock-article-10',
      title: 'International Sports Championship Sees Upset Victory',
      summary: 'Underdog team wins championship in stunning upset, defeating longtime champions.',
      content: 'Underdog team wins championship in stunning upset, defeating longtime champions. The victory came down to a dramatic final moment that had fans on the edge of their seats. The team\'s victory is being celebrated as one of the greatest sports stories of the decade.',
      author: 'Chris Taylor',
      publishedAt: new Date(now.getTime() - 10 * 60 * 60 * 1000).toISOString(),
      source: 'Sports Network',
      url: 'https://example.com/article-10',
      imageUrl: 'https://picsum.photos/800/600?random=10',
    },
  ];
}
